In [56]:
import pandas as pd

gdp = pd.read_csv('gdp_per_capita.csv')
# gdp = pd.read_csv('gdp_per_capita.xlsx') for excel file
# gdp = pd.read_csv('gdp_per_capita.txt',delimiter ='\t') fro txt file
gdp

,Country Name,Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24712.493263,26441.619936,26893.011506,28396.908423,28452.170615,29350.805019,30253.279358,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,147.612227,147.014904,156.189192,182.243917,162.347592,180.214908,190.845484,192.337167,...,1736.166560,1713.899299,1703.596298,1549.037940,1431.778723,1573.063386,1574.978648,1530.059177,1359.618224,NaN
2,Afghanistan,AFG,59.773234,59.860900,58.458009,78.706429,82.095307,101.108325,137.594298,160.898434,...,638.845852,624.315455,614.223342,556.007221,512.012778,516.679862,485.668419,494.179350,516.747871,NaN
3,Africa Western and Central,AFW,107.932233,113.081647,118.831107,123.442888,131.854402,138.526332,144.326212,128.582470,...,1965.118485,2157.481149,2212.853135,1894.310195,1673.835527,1613.473553,1704.139603,1777.918672,1710.073363,NaN
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5100.097027,5254.881126,5408.411700,4166.979833,3506.073128,4095.810057,3289.643995,2809.626088,1776.166868,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3410.859780,3704.784221,3902.676013,3520.766449,3759.560246,4009.380987,4384.048892,4416.108358,4346.637931,NaN
262,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1446.536472,1607.152173,1674.002572,1601.830063,1152.720966,964.264811,758.145242,NaN,NaN,NaN
263,South Africa,ZAF,443.009920,454.962013,473.011405,511.497364,548.996058,584.704163,621.220543,675.135345,...,8222.197279,7467.079185,6988.808739,6259.839681,5756.965741,6690.939847,7005.095413,6624.761865,5655.867654,NaN
264,Zambia,ZMB,232.188564,220.042067,212.578449,213.896759,242.384473,303.281740,343.373670,360.201239,...,1763.069442,1878.346811,1762.427817,1338.290927,1280.806543,1535.196574,1516.368371,1305.001031,985.132436,NaN
265,Zimbabwe,ZWE,278.813847,280.828663,276.688233,277.479715,281.558896,293.308788,277.234532,292.270533,...,1304.968011,1429.998461,1434.896277,1445.069702,1464.588957,1235.189032,1254.642265,1316.740657,1214.509820,NaN

In [4]:
gdp.columns

Index(['Country Name', 'Code', '1960', '1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974',
       '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', 'Unnamed: 65'],
      dtype='object')

In [13]:
gdp['Country Name'][121]

'Kenya'

In [19]:
gdp.iloc[121:131]

,Country Name,Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
121,Kenya,KEN,97.445501,94.651293,100.394495,103.778721,108.293688,104.711674,118.207910,120.987591,...,1271.815383,1354.820833,1462.220052,1464.554009,1525.235192,1633.491216,1794.091175,1912.647867,1878.580703,NaN
122,Kyrgyz Republic,KGZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1177.974735,1282.437162,1279.769783,1121.082835,1120.666513,1242.769643,1308.140165,1374.032105,1173.611304,NaN
123,Cambodia,KHM,111.342441,109.460350,109.481170,117.823450,123.645925,134.304280,138.842975,144.011778,...,950.880346,1013.420536,1093.495976,1162.904995,1269.591499,1385.260066,1512.126989,1643.121389,1543.669258,NaN
124,Kiribati,KIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1788.691439,1715.814321,1642.820129,1542.616465,1584.738015,1640.571205,1727.845001,1601.861869,1653.540297,NaN
125,St. Kitts and Nevis,KNA,241.539163,243.832122,246.101178,253.977446,268.718051,276.248904,299.250857,353.303331,...,16046.486935,16685.947591,18051.179035,18028.973431,19541.127833,20384.747881,20567.499114,22046.689912,18437.748924,NaN
126,"Korea, Rep.",KOR,158.249303,93.828649,106.148506,146.314342,123.603495,108.722131,133.474849,161.159931,...,25466.760517,27182.734310,29249.575221,28732.231076,29288.870439,31616.843400,33422.944210,31936.796353,31631.469451,NaN
127,Kuwait,KWT,NaN,NaN,NaN,NaN,NaN,4443.452338,4571.155742,4230.847778,...,51979.120690,49388.053380,44062.340913,29869.552753,27653.157620,29759.467475,33399.060437,32373.251122,24811.769710,NaN
128,Latin America & Caribbean (excluding high income),LAC,NaN,356.009889,376.502518,369.285249,411.794711,434.672175,467.834531,464.073370,...,9674.231156,9829.893489,9776.346543,8240.814501,7930.901915,8744.995172,8408.174698,8226.236324,6779.199717,NaN
129,Lao PDR,LAO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1581.628710,1831.936916,1999.958203,2140.044323,2324.400917,2455.211559,2569.093892,2635.800015,2629.714583,NaN
130,Lebanon,LBN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7952.151266,7933.233320,7687.759336,7663.920232,7653.733630,7819.604670,8058.444337,7578.172368,4649.547646,NaN

In [21]:
gdp.iloc[121,0]

'Kenya'

In [22]:
for index ,row in gdp.iterrows():
    print(index,row['Country Name'])

0 Aruba
1 Africa Eastern and Southern
2 Afghanistan
3 Africa Western and Central
4 Angola
5 Albania
6 Andorra
7 Arab World
8 United Arab Emirates
9 Argentina
10 Armenia
11 American Samoa
12 Antigua and Barbuda
13 Australia
14 Austria
15 Azerbaijan
16 Burundi
17 Belgium
18 Benin
19 Burkina Faso
20 Bangladesh
21 Bulgaria
22 Bahrain
23 Bahamas, The
24 Bosnia and Herzegovina
25 Belarus
26 Belize
27 Bermuda
28 Bolivia
29 Brazil
30 Barbados
31 Brunei Darussalam
32 Bhutan
33 Botswana
34 Central African Republic
35 Canada
36 Central Europe and the Baltics
37 Switzerland
38 Channel Islands
39 Chile
40 China
41 Cote d'Ivoire
42 Cameroon
43 Congo, Dem. Rep.
44 Congo, Rep.
45 Colombia
46 Comoros
47 Cabo Verde
48 Costa Rica
49 Caribbean small states
50 Cuba
51 Curacao
52 Cayman Islands
53 Cyprus
54 Czech Republic
55 Germany
56 Djibouti
57 Dominica
58 Denmark
59 Dominican Republic
60 Algeria
61 East Asia & Pacific (excluding high income)
62 Early-demographic dividend
63 East Asia & Pacific
64 Europe & Central Asia (excluding high income)
65 Europe & Central Asia
66 Ecuador
67 Egypt, Arab Rep.
68 Euro area
69 Eritrea
70 Spain
71 Estonia
72 Ethiopia
73 European Union
74 Fragile and conflict affected situations
75 Finland
76 Fiji
77 France
78 Faroe Islands
79 Micronesia, Fed. Sts.
80 Gabon
81 United Kingdom
82 Georgia
83 Ghana
84 Gibraltar
85 Guinea
86 Gambia, The
87 Guinea-Bissau
88 Equatorial Guinea
89 Greece
90 Grenada
91 Greenland
92 Guatemala
93 Guam
94 Guyana
95 High income
96 Hong Kong SAR, China
97 Honduras
98 Heavily indebted poor countries (HIPC)
99 Croatia
100 Haiti
101 Hungary
102 IBRD only
103 IDA & IBRD total
104 IDA total
105 IDA blend
106 Indonesia
107 IDA only
108 Isle of Man
109 India
110 Not classified
111 Ireland
112 Iran, Islamic Rep.
113 Iraq
114 Iceland
115 Israel
116 Italy
117 Jamaica
118 Jordan
119 Japan
120 Kazakhstan
121 Kenya
122 Kyrgyz Republic
123 Cambodia
124 Kiribati
125 St. Kitts and Nevis
126 Korea, Rep.
127 Kuwait
128 Latin America & Caribbean (excluding high income)
129 Lao PDR
130 Lebanon
131 Liberia
132 Libya
133 St. Lucia
134 Latin America & Caribbean
135 Least developed countries: UN classification
136 Low income
137 Liechtenstein
138 Sri Lanka
139 Lower middle income
140 Low & middle income
141 Lesotho
142 Late-demographic dividend
143 Lithuania
144 Luxembourg
145 Latvia
146 Macao SAR, China
147 St. Martin (French part)
148 Morocco
149 Monaco
150 Moldova
151 Madagascar
152 Maldives
153 Middle East & North Africa
154 Mexico
155 Marshall Islands
156 Middle income
157 North Macedonia
158 Mali
159 Malta
160 Myanmar
161 Middle East & North Africa (excluding high income)
162 Montenegro
163 Mongolia
164 Northern Mariana Islands
165 Mozambique
166 Mauritania
167 Mauritius
168 Malawi
169 Malaysia
170 North America
171 Namibia
172 New Caledonia
173 Niger
174 Nigeria
175 Nicaragua
176 Netherlands
177 Norway
178 Nepal
179 Nauru
180 New Zealand
181 OECD members
182 Oman
183 Other small states
184 Pakistan
185 Panama
186 Peru
187 Philippines
188 Palau
189 Papua New Guinea
190 Poland
191 Pre-demographic dividend
192 Puerto Rico
193 Korea, Dem. People's Rep.
194 Portugal
195 Paraguay
196 West Bank and Gaza
197 Pacific island small states
198 Post-demographic dividend
199 French Polynesia
200 Qatar
201 Romania
202 Russian Federation
203 Rwanda
204 South Asia
205 Saudi Arabia
206 Sudan
207 Senegal
208 Singapore
209 Solomon Islands
210 Sierra Leone
211 El Salvador
212 San Marino
213 Somalia
214 Serbia
215 Sub-Saharan Africa (excluding high income)
216 South Sudan
217 Sub-Saharan Africa
218 Small states
219 Sao Tome and Principe
220 Suriname
221 Slovak Republic
222 Slovenia
223 Sweden
224 Eswatini
225 Sint Maarten (Dutch part)
226 Seychelles
227 Syrian Arab Republic
228 Turks and Caicos Islands
229 Chad
230 East Asia & Pacific (IDA & IBRD countries)
231 Europe & Central Asia (IDA & IBRD countries)
232 Togo
233 Thailand
234 Tajikistan
235 Turkmenistan
236 Latin America & the Caribbean (IDA & IBRD countries)
237 Timor-Leste
238 Middle East & North Africa (IDA & IBRD countries)
239 Tonga
240 South Asia (IDA & IBRD)
241 Sub-Saharan Africa (IDA & IBRD countries)
242 Trinidad and Tobago
243 Tunisia
244 Turkey
245 Tuvalu
246 Tanzania
247 Uganda
248 Ukraine
249 Upper middle income
250 Uruguay
251 United States
252 Uzbekistan
253 St. Vincent and the Grenadines
254 Venezuela, RB
255 British Virgin Islands
256 Virgin Islands (U.S.)
257 Vietnam
258 Vanuatu
259 World
260 Samoa
261 Kosovo
262 Yemen, Rep.
263 South Africa
264 Zambia
265 Zimbabwe

In [26]:
gdp.loc[gdp['2009']>= 20000]

,Country Name,Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24712.493263,26441.619936,26893.011506,28396.908423,28452.170615,29350.805019,30253.279358,NaN,NaN,NaN
6,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38686.461264,39540.724814,41303.929371,35770.776704,37475.635059,38964.904478,41791.969837,40897.330873,NaN,NaN
8,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40976.490746,42412.639500,43751.805648,38663.400503,38141.867131,40644.791190,43839.324487,42701.443045,36284.555243,NaN
13,Australia,AUS,1810.619230,1877.616638,1854.656834,1967.116537,2131.377948,2281.098797,2343.995290,2580.271096,...,68027.841707,68156.627916,62511.690590,56707.022077,49881.763714,53934.250175,57180.779400,54875.285956,51692.842748,NaN
14,Austria,AUT,935.460427,1031.815004,1087.834243,1167.000532,1269.412583,1374.532140,1486.968606,1569.667183,...,48567.695286,50716.708706,51717.495941,44178.047378,45276.831435,47312.006233,51461.433215,50114.401110,48586.801321,NaN
17,Belgium,BEL,1273.691659,1350.197673,1438.523233,1535.023729,1701.846276,1835.594766,1957.626080,2086.636005,...,44673.115876,46744.662544,47700.540360,40991.808138,41984.103034,44089.310088,47519.553097,46591.491607,45159.348223,NaN
23,"Bahamas, The",BHS,1550.267699,1651.317673,1752.840006,1867.010351,1994.440497,2144.739089,2322.705816,2556.634267,...,29485.864223,28583.023298,30065.160202,31776.055585,31732.919140,32376.509172,33290.028135,33799.417694,25194.025144,NaN
27,Bermuda,BMU,1902.402119,1961.538169,2020.385965,2020.265247,2199.727007,2282.216546,2630.850466,2982.749704,...,98431.865181,99471.638898,98467.683994,102005.625642,106885.878489,111820.581466,113023.185594,117098.446325,107079.479837,NaN
31,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,1113.783042,1237.563579,1236.419664,...,47739.557693,44740.859424,41725.867522,31164.036253,27158.405654,28571.608291,31628.476257,31085.961926,27442.953828,NaN
35,Canada,CAN,2259.294285,2240.433039,2268.585346,2374.498448,2555.111146,2770.361804,3047.106147,3217.159294,...,52669.089963,52635.174958,50955.998323,43596.135537,42315.603706,45129.356440,46548.520360,46338.340956,43294.648163,NaN
37,Switzerland,CHE,1787.360348,1971.316323,2131.391652,2294.182847,2501.293190,2620.475547,2784.733548,2960.722586,...,86547.670891,88109.486752,89684.707580,84776.142166,83073.280082,83352.088653,86388.404953,85334.519462,87097.036450,NaN
52,Cayman Islands,CYM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72777.148489,73514.668683,74990.433222,76284.193929,78471.628732,81513.163022,86059.739217,91392.642588,85082.526856,NaN
53,Cyprus,CYP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28912.156939,27729.192699,27163.332966,23408.336682,24605.920833,26608.875092,29334.110935,29206.076719,27527.845306,NaN
55,Germany,DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43858.363055,46285.764069,47959.993274,41086.729674,42107.517270,44542.295204,47950.180814,46794.899292,46208.429472,NaN
58,Denmark,DNK,NaN,NaN,NaN,NaN,NaN,NaN,2487.136181,2700.746290,...,58507.508052,61191.193704,62548.984733,53254.856370,54663.998372,57610.098180,61591.928870,59775.735096,61063.316430,NaN
65,Europe & Central Asia,ECS,NaN,NaN,NaN,NaN,NaN,NaN,1032.937571,1102.240970,...,25133.279822,26143.500333,26368.361516,22619.698841,22446.168750,23670.079714,25290.331447,24906.436727,23955.305158,NaN
68,Euro area,EMU,923.187341,1005.022273,1106.286139,1229.910396,1355.645823,1468.536265,1589.042333,1714.402853,...,37598.009647,39109.308441,39859.682067,34374.493607,35139.823585,37062.140361,40038.187167,39188.636538,37967.801866,NaN
70,Spain,ESP,396.392253,450.053289,520.206131,609.487384,675.241639,774.761609,889.659872,968.306782,...,28324.429336,29059.547952,29461.550334,25732.018365,26505.343216,28100.586242,30349.752098,29555.315699,27063.193918,NaN
73,European Union,EUU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33160.516259,34569.647454,35245.859732,30474.497551,31168.436044,33023.790904,35737.301250,35083.807485,34148.919900,NaN
75,Finland,FIN,1179.353011,1327.427224,1411.702398,1522.319242,1707.503938,1882.086858,2010.213456,2034.189050,...,47710.790217,49878.043244,50260.299859,42784.698362,43784.283962,46297.496346,49964.499910,48628.641762,48744.988127,NaN
77,France,FRA,1334.689512,1428.046001,1578.284538,1744.640123,1909.541620,2038.163102,2186.474592,2343.104503,...,40874.700393,42592.935385,43011.263103,36638.184929,37037.374186,38685.258494,41572.485010,40578.644285,39030.360371,NaN
78,Faroe Islands,FRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49459.717234,54843.319285,59433.834573,52400.297276,56854.102654,59993.090627,62918.146194,64225.264905,NaN,NaN
81,United Kingdom,GBR,1397.594803,1472.385714,1525.775853,1613.456884,1748.288118,1873.567774,1986.747159,2058.781882,...,42686.800052,43713.814124,47787.241298,45404.567773,41499.555703,40857.755583,43646.951971,43070.498360,41059.168809,NaN
89,Greece,GRC,520.322744,590.780055,617.057758,695.228624,783.705881,899.281239,997.430467,1068.114556,...,21914.251729,21781.595347,21587.957551,18076.606755,17911.799377,18536.190718,19747.342584,19133.757764,17622.541003,NaN
91,Greenland,GRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45936.765952,47535.589945,50484.927574,44536.401308,48181.874188,50765.695648,54270.822306,53041.303310,NaN,NaN
93,Guam,GUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32908.306769,33656.453574,34843.205575,35829.250360,36214.006922,36601.919881,36556.674911,38040.586987,34624.340129,NaN
95,High income,HIC,1402.801006,1466.132519,1562.408304,1661.973305,1791.845278,1923.145958,2086.918156,2216.603616,...,42143.611586,42400.673269,43066.085371,40474.322806,41112.509403,42754.564220,45240.562753,45462.371682,44003.413710,NaN
96,"Hong Kong SAR, China",HKG,429.442874,436.754412,487.821134,565.727810,629.591526,676.805507,685.926614,723.239226,...,36730.876700,38403.777715,40315.285564,42431.888282,43731.106825,46165.856512,48542.681870,48354.473367,46323.863442,NaN
108,Isle of Man,IMN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,79148.332251,83357.132684,92334.646314,85126.970469,82197.126770,83477.834285,89112.667716,86481.552591,NaN,NaN
111,Ireland,IRL,685.614712,739.276406,797.006288,852.135302,965.135423,1023.773726,1074.506506,1152.004952,...,49028.827394,51518.388103,55525.897251,61987.550998,62818.966365,69601.683882,79068.974612,80886.615739,85267.764744,NaN
114,Iceland,ISL,1414.982269,1418.125870,1562.230730,1831.705656,2297.920643,2723.520950,3215.694178,3125.649492,...,45995.547879,49804.982998,54576.744815,52951.681511,61987.926362,72010.149032,74469.804059,68941.462227,59270.180051,NaN
115,Israel,ISR,1229.174748,1436.384439,1094.635848,1257.811405,1375.892256,1429.314605,1513.883606,1468.123862,...,32667.606872,36499.456108,37847.649943,35808.436429,37330.261797,40774.129607,42063.453127,43951.247731,44168.943636,NaN
116,Italy,ITA,804.492623,887.336745,990.260152,1126.019337,1222.544540,1304.453817,1402.442354,1533.692877,...,35053.526244,35549.974697,35518.415292,30230.226302,30939.714246,32326.674211,34605.262725,33641.633751,31714.220947,NaN
119,Japan,JPN,475.319076,568.907743,639.640785,724.693762,843.616879,928.518849,1068.558440,1239.318377,...,49145.280431,40898.647896,38475.395246,34960.639384,39400.739356,38891.086272,39808.168561,40777.608697,40193.252445,NaN
127,Kuwait,KWT,NaN,NaN,NaN,NaN,NaN,4443.452338,4571.155742,4230.847778,...,51979.120690,49388.053380,44062.340913,29869.552753,27653.157620,29759.467475,33399.060437,32373.251122,24811.769710,NaN
137,Liechtenstein,LIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,149010.224899,173030.208279,178864.851914,167313.266280,165642.386276,171253.964254,180366.715198,175813.875592,NaN,NaN
144,Luxembourg,LUX,2242.015817,2222.366366,2311.798849,2441.038555,2755.633117,2780.092719,2900.433218,2909.660629,...,112591.116203,119966.034889,123514.196686,105419.608507,106826.726449,109921.031444,117197.481694,113218.713350,116014.602497,NaN
146,"Macao SAR, China",MAC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76572.151787,89260.757104,93022.875142,74818.948126,73545.758237,81019.473767,87526.079991,86197.365694,39403.135907,NaN
149,Monaco,MCO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,157520.219427,177673.745368,189432.370013,165989.505114,170028.655718,167517.059728,185978.609251,189487.147128,173688.189360,NaN
159,Malta,MLT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22527.636756,24771.076578,26754.268445,24921.603682,25741.446061,28250.697775,30672.292244,30186.195962,27884.642827,NaN
170,North America,NAC,2939.448335,2991.592897,3155.097538,3283.141453,3480.426945,3729.969704,4044.247215,4231.867351,...,51717.787008,53068.032546,54648.019342,55542.966073,56451.517501,58605.344292,61391.269769,63342.982182,61502.095945,NaN
172,New Caledonia,NCL,NaN,NaN,NaN,NaN,NaN,1763.475053,1756.219639,1865.665984,...,37294.022813,38503.253847,39675.566312,32520.294163,32391.197218,33976.555554,36382.487656,34788.529282,NaN,NaN
176,Netherlands,NLD,1068.784587,1159.392357,1240.677894,1328.036649,1541.947365,1708.096356,1835.801424,1991.360686,...,50073.005656,52184.061850,52830.174233,45175.231893,46007.852921,48554.992276,53018.629356,52476.273253,52397.116713,NaN
177,Norway,NOR,1441.755660,1560.324931,1667.247430,1775.582655,1937.884614,2164.468823,2317.194884,2514.043772,...,101524.141852,102913.450844,97019.182753,74355.515858,70460.560532,75496.754058,82267.809316,75719.752897,67329.677791,NaN
180,New Zealand,NZL,2312.949992,2343.292213,2448.628633,2622.220271,2813.546976,2151.294927,2191.312542,2188.399139,...,39973.380759,42976.649588,44572.898754,38630.726589,40080.494114,42992.895274,43306.070003,42755.216263,41441.466667,NaN
181,OECD members,OED,1335.440329,1384.981279,1474.283622,1567.435760,1690.114618,1810.724416,1963.160301,2082.746624,...,37174.625388,37431.363240,37962.663697,35612.506130,36072.084458,37407.264334,39372.835920,39552.661796,38218.872374,NaN
192,Puerto Rico,PRI,717.514843,777.215027,854.744805,931.751666,1006.434446,1110.832691,1207.811824,1335.274112,...,27944.733894,28513.165735,28981.457331,29763.488301,30627.163402,31108.760570,31604.701514,32850.548612,32290.921136,NaN
194,Portugal,PRT,360.499299,382.729947,407.852844,432.511730,468.781082,520.910659,575.007681,646.822720,...,20564.889862,21647.041812,22074.300763,19242.366471,19978.401215,21437.347504,23551.048291,23330.817289,22176.296712,NaN
198,Post-demographic dividend,PST,1385.490405,1447.273257,1543.634895,1643.059028,1771.965648,1903.970001,2067.070482,2197.736217,...,42256.716991,42489.684973,43159.476701,40694.350065,41442.762383,43033.440798,45492.802018,45819.480083,44475.189167,NaN
200,Qatar,QAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85075.986537,85050.684341,83858.340458,63039.112626,57162.968012,59124.867271,65907.948435,62276.428694,50124.385936,NaN
208,Singapore,SGP,428.058980,449.151071,472.085824,511.205575,485.533858,516.535303,566.807678,626.033528,...,55546.488539,56967.425794,57562.530794,55646.618747,56848.175392,61176.456361,66679.046490,65640.707948,59797.752180,NaN
212,San Marino,SMR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49988.463631,51570.983955,50817.330825,42662.902651,43828.232461,45399.029061,48996.592249,47731.208540,NaN,NaN
222,Slovenia,SVN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22643.100252,23496.602499,24214.922072,20881.766930,21663.643414,23455.944726,26104.102789,25942.954774,25517.330665,NaN
223,Sweden,SWE,2114.002973,2288.921701,2468.694589,2657.022505,2941.048899,3206.099170,3454.429789,3720.926845,...,58037.821319,61126.943196,60020.360458,51545.483610,51965.157153,53791.508730,54589.060386,51939.429745,52274.408787,NaN
228,Turks and Caicos Islands,TCA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21345.025978,21715.313967,23778.519126,26183.885044,28241.479293,27545.128785,29553.136698,31350.866628,23879.926649,NaN
251,United States,USA,3007.123445,3066.562869,3243.843078,3374.515171,3573.941185,3827.527110,4146.316646,4336.426587,...,51602.931046,53106.536767,55049.988327,56863.371496,58021.400500,60109.655726,63064.418410,65279.529026,63593.443621,NaN
256,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37795.319259,34597.976694,33045.364380,34007.352941,35324.974887,35365.069304,36448.257493,38136.665760,NaN,NaN

In [28]:
gdp.describe()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
count,128.000000,134.000000,137.000000,137.000000,137.000000,148.000000,151.000000,154.000000,159.000000,159.000000,...,257.000000,258.000000,258.000000,257.000000,256.000000,256.000000,256.000000,253.000000,242.000000,0.0
mean,482.725314,491.115624,513.103203,544.566319,590.805091,654.822693,710.326019,725.993794,742.735017,804.348363,...,16120.560273,16659.720923,16964.258521,15359.980640,15524.456868,16308.827347,17288.675629,17144.609643,14354.539354,NaN
std,626.040168,639.846845,669.060194,708.534576,774.925619,864.084238,935.096499,966.070357,994.686146,1071.190027,...,23550.237516,25086.503778,25768.767745,23277.449054,23522.761455,24336.089896,25989.582741,25903.117527,21898.003148,NaN
min,40.537211,26.308357,26.985920,28.449430,20.035487,16.596459,12.802812,12.915456,20.418277,20.700642,...,252.358871,256.975653,274.857836,305.549653,260.565221,253.826354,238.783467,228.213589,238.990726,NaN
25%,104.407303,109.078291,114.581807,121.762130,123.645925,138.512407,145.574804,155.377495,154.043379,160.648668,...,1965.118485,2092.400443,2156.756410,2049.851666,2093.428898,2101.842601,2202.590063,2246.625578,1936.184305,NaN
50%,197.897848,197.158225,203.437370,213.896759,234.633358,249.112369,262.312268,252.705895,281.925786,293.387951,...,6528.971775,6797.232338,6655.280874,6175.876030,5921.203011,6336.133639,6962.584227,6853.693411,5606.538092,NaN
75%,478.826988,475.192902,520.206131,583.411562,629.591526,683.030310,780.032061,750.374486,766.275654,826.348388,...,19870.801212,20140.951340,20148.318040,18028.973431,18356.000551,19689.335613,19952.381716,19575.768481,15650.348914,NaN
max,3007.123445,3066.562869,3243.843078,3374.515171,3573.941185,4443.452338,4571.155742,4336.426587,4695.923390,5032.144743,...,157520.219427,177673.745368,189432.370013,167313.266280,170028.655718,171253.964254,185978.609251,189487.147128,173688.189360,NaN

In [31]:
gdp.sort_values(['2008'], ascending =False)

,Country Name,Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
149,Monaco,MCO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,157520.219427,177673.745368,189432.370013,165989.505114,170028.655718,167517.059728,185978.609251,189487.147128,173688.189360,NaN
137,Liechtenstein,LIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,149010.224899,173030.208279,178864.851914,167313.266280,165642.386276,171253.964254,180366.715198,175813.875592,NaN,NaN
144,Luxembourg,LUX,2242.015817,2222.366366,2311.798849,2441.038555,2755.633117,2780.092719,2900.433218,2909.660629,...,112591.116203,119966.034889,123514.196686,105419.608507,106826.726449,109921.031444,117197.481694,113218.713350,116014.602497,NaN
27,Bermuda,BMU,1902.402119,1961.538169,2020.385965,2020.265247,2199.727007,2282.216546,2630.850466,2982.749704,...,98431.865181,99471.638898,98467.683994,102005.625642,106885.878489,111820.581466,113023.185594,117098.446325,107079.479837,NaN
177,Norway,NOR,1441.755660,1560.324931,1667.247430,1775.582655,1937.884614,2164.468823,2317.194884,2514.043772,...,101524.141852,102913.450844,97019.182753,74355.515858,70460.560532,75496.754058,82267.809316,75719.752897,67329.677791,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,French Polynesia,PYF,NaN,NaN,NaN,NaN,NaN,1889.242414,2229.752737,2210.064698,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,Somalia,SOM,65.479716,68.106397,70.813049,73.607204,76.480398,79.428813,81.871114,84.198965,...,NaN,350.168162,374.114781,386.437817,389.822062,384.463401,389.831395,419.394808,438.255166,NaN
225,Sint Maarten (Dutch part),SXM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28460.332615,27942.880540,33043.688381,32274.890552,31616.681699,29369.056828,29160.103811,NaN,NaN,NaN
255,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
gdp['Total'] = gdp.iloc[:,11:].sum(axis=1)

In [33]:
gdp.columns

Index(['Country Name', 'Code', '1960', '1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974',
       '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', 'Unnamed: 65', 'Total'],
      dtype='object')

In [51]:
twentyonec=gdp.sort_values(['Total'], ascending =False)
twentyonec.reset_index(drop = True, inplace = True )
twentyonec.to_csv('twentyone.csv')
twentyonec.iloc[1:50]

,Country Name,Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65,Total
1,Liechtenstein,LIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,173030.208279,178864.851914,167313.266280,165642.386276,171253.964254,180366.715198,175813.875592,NaN,NaN,3.729348e+06
2,Luxembourg,LUX,2242.015817,2222.366366,2311.798849,2441.038555,2755.633117,2780.092719,2900.433218,2909.660629,...,119966.034889,123514.196686,105419.608507,106826.726449,109921.031444,117197.481694,113218.713350,116014.602497,NaN,2.777235e+06
3,Bermuda,BMU,1902.402119,1961.538169,2020.385965,2020.265247,2199.727007,2282.216546,2630.850466,2982.749704,...,99471.638898,98467.683994,102005.625642,106885.878489,111820.581466,113023.185594,117098.446325,107079.479837,NaN,2.597622e+06
4,Switzerland,CHE,1787.360348,1971.316323,2131.391652,2294.182847,2501.293190,2620.475547,2784.733548,2960.722586,...,88109.486752,89684.707580,84776.142166,83073.280082,83352.088653,86388.404953,85334.519462,87097.036450,NaN,2.171541e+06
5,Norway,NOR,1441.755660,1560.324931,1667.247430,1775.582655,1937.884614,2164.468823,2317.194884,2514.043772,...,102913.450844,97019.182753,74355.515858,70460.560532,75496.754058,82267.809316,75719.752897,67329.677791,NaN,2.166704e+06
6,Qatar,QAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85050.684341,83858.340458,63039.112626,57162.968012,59124.867271,65907.948435,62276.428694,50124.385936,NaN,1.752447e+06
7,Denmark,DNK,NaN,NaN,NaN,NaN,NaN,NaN,2487.136181,2700.746290,...,61191.193704,62548.984733,53254.856370,54663.998372,57610.098180,61591.928870,59775.735096,61063.316430,NaN,1.666965e+06
8,United States,USA,3007.123445,3066.562869,3243.843078,3374.515171,3573.941185,3827.527110,4146.316646,4336.426587,...,53106.536767,55049.988327,56863.371496,58021.400500,60109.655726,63064.418410,65279.529026,63593.443621,NaN,1.624685e+06
9,Iceland,ISL,1414.982269,1418.125870,1562.230730,1831.705656,2297.920643,2723.520950,3215.694178,3125.649492,...,49804.982998,54576.744815,52951.681511,61987.926362,72010.149032,74469.804059,68941.462227,59270.180051,NaN,1.620924e+06
10,Sweden,SWE,2114.002973,2288.921701,2468.694589,2657.022505,2941.048899,3206.099170,3454.429789,3720.926845,...,61126.943196,60020.360458,51545.483610,51965.157153,53791.508730,54589.060386,51939.429745,52274.408787,NaN,1.617591e+06
11,North America,NAC,2939.448335,2991.592897,3155.097538,3283.141453,3480.426945,3729.969704,4044.247215,4231.867351,...,53068.032546,54648.019342,55542.966073,56451.517501,58605.344292,61391.269769,63342.982182,61502.095945,NaN,1.594575e+06
12,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42412.639500,43751.805648,38663.400503,38141.867131,40644.791190,43839.324487,42701.443045,36284.555243,NaN,1.550297e+06
13,Ireland,IRL,685.614712,739.276406,797.006288,852.135302,965.135423,1023.773726,1074.506506,1152.004952,...,51518.388103,55525.897251,61987.550998,62818.966365,69601.683882,79068.974612,80886.615739,85267.764744,NaN,1.453054e+06
14,Netherlands,NLD,1068.784587,1159.392357,1240.677894,1328.036649,1541.947365,1708.096356,1835.801424,1991.360686,...,52184.061850,52830.174233,45175.231893,46007.852921,48554.992276,53018.629356,52476.273253,52397.116713,NaN,1.438357e+06
15,Japan,JPN,475.319076,568.907743,639.640785,724.693762,843.616879,928.518849,1068.558440,1239.318377,...,40898.647896,38475.395246,34960.639384,39400.739356,38891.086272,39808.168561,40777.608697,40193.252445,NaN,1.384516e+06
16,Australia,AUS,1810.619230,1877.616638,1854.656834,1967.116537,2131.377948,2281.098797,2343.995290,2580.271096,...,68156.627916,62511.690590,56707.022077,49881.763714,53934.250175,57180.779400,54875.285956,51692.842748,NaN,1.362861e+06
17,Finland,FIN,1179.353011,1327.427224,1411.702398,1522.319242,1707.503938,1882.086858,2010.213456,2034.189050,...,49878.043244,50260.299859,42784.698362,43784.283962,46297.496346,49964.499910,48628.641762,48744.988127,NaN,1.360228e+06
18,Austria,AUT,935.460427,1031.815004,1087.834243,1167.000532,1269.412583,1374.532140,1486.968606,1569.667183,...,50716.708706,51717.495941,44178.047378,45276.831435,47312.006233,51461.433215,50114.401110,48586.801321,NaN,1.351652e+06
19,Canada,CAN,2259.294285,2240.433039,2268.585346,2374.498448,2555.111146,2770.361804,3047.106147,3217.159294,...,52635.174958,50955.998323,43596.135537,42315.603706,45129.356440,46548.520360,46338.340956,43294.648163,NaN,1.319767e+06
20,Isle of Man,IMN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83357.132684,92334.646314,85126.970469,82197.126770,83477.834285,89112.667716,86481.552591,NaN,NaN,1.311778e+06
21,Belgium,BEL,1273.691659,1350.197673,1438.523233,1535.023729,1701.846276,1835.594766,1957.626080,2086.636005,...,46744.662544,47700.540360,40991.808138,41984.103034,44089.310088,47519.553097,46591.491607,45159.348223,NaN,1.288588e+06
22,Germany,DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46285.764069,47959.993274,41086.729674,42107.517270,44542.295204,47950.180814,46794.899292,46208.429472,NaN,1.287203e+06
23,"Macao SAR, China",MAC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89260.757104,93022.875142,74818.948126,73545.758237,81019.473767,87526.079991,86197.365694,39403.135907,NaN,1.280654e+06
24,United Kingdom,GBR,1397.594803,1472.385714,1525.775853,1613.456884,1748.288118,1873.567774,1986.747159,2058.781882,...,43713.814124,47787.241298,45404.567773,41499.555703,40857.755583,43646.951971,43070.498360,41059.168809,NaN,1.253600e+06
25,Singapore,SGP,428.058980,449.151071,472.085824,511.205575,485.533858,516.535303,566.807678,626.033528,...,56967.425794,57562.530794,55646.618747,56848.175392,61176.456361,66679.046490,65640.707948,59797.752180,NaN,1.240094e+06
26,France,FRA,1334.689512,1428.046001,1578.284538,1744.640123,1909.541620,2038.163102,2186.474592,2343.104503,...,42592.935385,43011.263103,36638.184929,37037.374186,38685.258494,41572.485010,40578.644285,39030.360371,NaN,1.224891e+06
27,Post-demographic dividend,PST,1385.490405,1447.273257,1543.634895,1643.059028,1771.965648,1903.970001,2067.070482,2197.736217,...,42489.684973,43159.476701,40694.350065,41442.762383,43033.440798,45492.802018,45819.480083,44475.189167,NaN,1.214279e+06
28,High income,HIC,1402.801006,1466.132519,1562.408304,1661.973305,1791.845278,1923.145958,2086.918156,2216.603616,...,42400.673269,43066.085371,40474.322806,41112.509403,42754.564220,45240.562753,45462.371682,44003.413710,NaN,1.209746e+06
29,Cayman Islands,CYM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73514.668683,74990.433222,76284.193929,78471.628732,81513.163022,86059.739217,91392.642588,85082.526856,NaN,1.196591e+06
30,Greenland,GRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47535.589945,50484.927574,44536.401308,48181.874188,50765.695648,54270.822306,53041.303310,NaN,NaN,1.144815e+06
31,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39540.724814,41303.929371,35770.776704,37475.635059,38964.904478,41791.969837,40897.330873,NaN,NaN,1.121189e+06
32,San Marino,SMR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51570.983955,50817.330825,42662.902651,43828.232461,45399.029061,48996.592249,47731.208540,NaN,NaN,1.110246e+06
33,Euro area,EMU,923.187341,1005.022273,1106.286139,1229.910396,1355.645823,1468.536265,1589.042333,1714.402853,...,39109.308441,39859.682067,34374.493607,35139.823585,37062.140361,40038.187167,39188.636538,37967.801866,NaN,1.103629e+06
34,Kuwait,KWT,NaN,NaN,NaN,NaN,NaN,4443.452338,4571.155742,4230.847778,...,49388.053380,44062.340913,29869.552753,27653.157620,29759.467475,33399.060437,32373.251122,24811.769710,NaN,1.080641e+06
35,OECD members,OED,1335.440329,1384.981279,1474.283622,1567.435760,1690.114618,1810.724416,1963.160301,2082.746624,...,37431.363240,37962.663697,35612.506130,36072.084458,37407.264334,39372.835920,39552.661796,38218.872374,NaN,1.075279e+06
36,"Hong Kong SAR, China",HKG,429.442874,436.754412,487.821134,565.727810,629.591526,676.805507,685.926614,723.239226,...,38403.777715,40315.285564,42431.888282,43731.106825,46165.856512,48542.681870,48354.473367,46323.863442,NaN,1.052664e+06
37,Italy,ITA,804.492623,887.336745,990.260152,1126.019337,1222.544540,1304.453817,1402.442354,1533.692877,...,35549.974697,35518.415292,30230.226302,30939.714246,32326.674211,34605.262725,33641.633751,31714.220947,NaN,1.046184e+06
38,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,1113.783042,1237.563579,1236.419664,...,44740.859424,41725.867522,31164.036253,27158.405654,28571.608291,31628.476257,31085.961926,27442.953828,NaN,1.023233e+06
39,New Zealand,NZL,2312.949992,2343.292213,2448.628633,2622.220271,2813.546976,2151.294927,2191.312542,2188.399139,...,42976.649588,44572.898754,38630.726589,40080.494114,42992.895274,43306.070003,42755.216263,41441.466667,NaN,9.925972e+05
40,Faroe Islands,FRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54843.319285,59433.834573,52400.297276,56854.102654,59993.090627,62918.146194,64225.264905,NaN,NaN,9.736010e+05
41,European Union,EUU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34569.647454,35245.859732,30474.497551,31168.436044,33023.790904,35737.301250,35083.807485,34148.919900,NaN,9.359438e+05
42,New Caledonia,NCL,NaN,NaN,NaN,NaN,NaN,1763.475053,1756.219639,1865.665984,...,38503.253847,39675.566312,32520.294163,32391.197218,33976.555554,36382.487656,34788.529282,NaN,NaN,9.312406e+05
43,"Bahamas, The",BHS,1550.267699,1651.317673,1752.840006,1867.010351,1994.440497,2144.739089,2322.705816,2556.634267,...,28583.023298,30065.160202,31776.055585,31732.919140,32376.509172,33290.028135,33799.417694,25194.025144,NaN,9.277729e+05
44,Spain,ESP,396.392253,450.053289,520.206131,609.487384,675.241639,774.761609,889.659872,968.306782,...,29059.547952,29461.550334,25732.018365,26505.343216,28100.586242,30349.752098,29555.315699,27063.193918,NaN,8.147907e+05
45,Puerto Rico,PRI,717.514843,777.215027,854.744805,931.751666,1006.434446,1110.832691,1207.811824,1335.274112,...,28513.165735,28981.457331,29763.488301,30627.163402,31108.760570,31604.701514,32850.548612,32290.921136,NaN,7.526176e+05
46,Israel,ISR,1229.174748,1436.384439,1094.635848,1257.811405,1375.892256,1429.314605,1513.883606,1468.123862,...,36499.456108,37847.649943,35808.436429,37330.261797,40774.129607,42063.453127,43951.247731,44168.943636,NaN,7.475857e+05
47,Cyprus,CYP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27729.192699,27163.332966,23408.336682,24605.920833,26608.875092,29334.110935,29206.076719,27527.845306,NaN,7.368536e+05
48,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26441.619936,26893.011506,28396.908423,28452.170615,29350.805019,30253.279358,NaN,NaN,NaN,6.689487e+05
49,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34597.976694,33045.364380,34007.352941,35324.974887,35365.069304,36448.257493,38136.665760,NaN,NaN,6.646928e+05

In [60]:
gdp.cumsum()

,Country Name,Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.471249e+04,2.644162e+04,2.689301e+04,2.839691e+04,2.845217e+04,2.935081e+04,3.025328e+04,NaN,NaN,NaN
1,ArubaAfrica Eastern and Southern,ABWAFE,147.612227,147.014904,156.189192,182.243917,162.347592,180.214908,190.845484,192.337167,...,2.644866e+04,2.815552e+04,2.859661e+04,2.994595e+04,2.988395e+04,3.092387e+04,3.182826e+04,1.530059e+03,1.359618e+03,NaN
2,ArubaAfrica Eastern and SouthernAfghanistan,ABWAFEAFG,207.385461,206.875804,214.647200,260.950346,244.442899,281.323233,328.439782,353.235601,...,2.708751e+04,2.877983e+04,2.921083e+04,3.050195e+04,3.039596e+04,3.144055e+04,3.231393e+04,2.024239e+03,1.876366e+03,NaN
3,ArubaAfrica Eastern and SouthernAfghanistanAfr...,ABWAFEAFGAFW,315.317694,319.957451,333.478307,384.393234,376.297301,419.849565,472.765994,481.818071,...,2.905262e+04,3.093732e+04,3.142368e+04,3.239626e+04,3.206980e+04,3.305402e+04,3.401807e+04,3.802157e+03,3.586439e+03,NaN
4,ArubaAfrica Eastern and SouthernAfghanistanAfr...,ABWAFEAFGAFWAGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.415272e+04,3.619220e+04,3.683210e+04,3.656324e+04,3.557587e+04,3.714983e+04,3.730771e+04,6.611783e+03,5.362606e+03,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,ArubaAfrica Eastern and SouthernAfghanistanAfr...,ABWAFEAFGAFWAGOALBANDARBAREARGARMASMATGAUSAUTA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.130247e+06,4.285825e+06,4.364919e+06,3.936870e+06,3.964606e+06,4.164634e+06,4.415367e+06,4.328340e+06,3.465943e+06,NaN
262,ArubaAfrica Eastern and SouthernAfghanistanAfr...,ABWAFEAFGAFWAGOALBANDARBAREARGARMASMATGAUSAUTA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.131694e+06,4.287433e+06,4.366593e+06,3.938472e+06,3.965759e+06,4.165598e+06,4.416125e+06,NaN,NaN,NaN
263,ArubaAfrica Eastern and SouthernAfghanistanAfr...,ABWAFEAFGAFWAGOALBANDARBAREARGARMASMATGAUSAUTA...,61277.837822,65308.622951,69805.872173,74114.209216,80416.354051,96317.167978,106638.620664,111150.572579,...,4.139916e+06,4.294900e+06,4.373581e+06,3.944732e+06,3.971516e+06,4.172289e+06,4.423130e+06,4.334964e+06,3.471599e+06,NaN
264,ArubaAfrica Eastern and SouthernAfghanistanAfr...,ABWAFEAFGAFWAGOALBANDARBAREARGARMASMATGAUSAUTA...,61510.026387,65528.665018,70018.450622,74328.105975,80658.738524,96620.449719,106981.994334,111510.773817,...,4.141679e+06,4.296778e+06,4.375344e+06,3.946070e+06,3.972796e+06,4.173825e+06,4.424646e+06,4.336269e+06,3.472584e+06,NaN
265,ArubaAfrica Eastern and SouthernAfghanistanAfr...,ABWAFEAFGAFWAGOALBANDARBAREARGARMASMATGAUSAUTA...,61788.840234,65809.493681,70295.138855,74605.585690,80940.297420,96913.758507,107259.228865,111803.044350,...,4.142984e+06,4.298208e+06,4.376779e+06,3.947515e+06,3.974261e+06,4.175060e+06,4.425901e+06,4.337586e+06,3.473799e+06,NaN